#!/bin/bash
#
# This script builds the Android release package.

set -e

pushd android
./gradlew assembleRelease
cp pptrustwalletcore/build/outputs/aar/pptrustwalletcore-release.aar ../build/pptrustwalletcore.aar
popd

echo "Now upload build/pptrustwalletcore.aar to https://github.com/taha-husain/pp-wallet-core/releases/tag/$(git describe --long --tags | cut -f 1 -d "-")"
